### ISSUE TITLE
Which NSProgress features are not supported?

### ISSUE THREAD

**Issue by JetForMe** [CharlesJS/CSProgress#3]
I'm trying to use [PromiseKit](http://github.com/mxcl/PromiseKit) more in my project, but progress reporting is an as-yet unsolved aspect. The advice is to use something like NSProgress to decouple progress reporting from the operations, and that makes sense, but as I looked into it, I quickly came across your project.

I'd like to start with NSProgress to see how things fare, and then migrate to CSProgress if I run into issues, but I want to make sure I don't use any unsupported features. What are they?

Thanks.

**Comment by CharlesJS** [comment]
Super late answering this one, but better late than never I suppose.

The "todo" section at the bottom of the README mentions the unsupported features. Most of them are fairly tangential to the core functionality of the class.
