### ISSUE TITLE
Can't remove children?

### ISSUE THREAD

**Issue by lmcd** [CharlesJS/CSProgress#4]
Is this just to maintain parity with `Progress`? I feel like this would add a lot of value if this was exposed publicly

**Comment by CharlesJS** [comment]
Do you have a specific use case for this?

**Comment by lmcd** [comment]
Lets say I have a tableview-style UI, with different sorts of cells each doing work under their own progress tree. I'd like a `Progress` that encapsulates all of the work these cells are doing - except the cells come in and out of view/memory as the user scrolls, so I'd like to remove items from the root `Progress` as they disappear off screen.

This root progress can then have its `fractionCompleted` wired up to a progress indicator.

Hope that makes sense.

**Comment by CharlesJS** [comment]
Why do you want to hide the progress of part of your operation simply because it's been scrolled out of the visible area? Having the progress bar's value jump around forwards and backwards just because you scrolled a view seems like a very strange UI to me.

**Comment by lmcd** [comment]
It’s for an indeterminate progress indicator and other non-UI purposes.

Also the given example is just a rough approximation of what I’m doing as I can’t actually talk about what I’m doing 😊

**Comment by CharlesJS** [comment]
For an indeterminate progress bar, you don't really need progress reporting at all. Just give each of your tasks a Boolean flag marking whether it's done or not, and `OR` them together to determine whether to show your progress bar or not.

**Comment by lmcd** [comment]
Yeah I can do that just fine, but automatically managing a group of child `Progress`es, and determining whether they're all 'done' or not is usually the job of `Progress`.

I'm using a tweaked version of this at the moment, I'll stick with it for now: https://gist.github.com/AvdLee/6c7353fab031f11f6c9e47594ee9cfa8

**Comment by lmcd** [comment]
Also, `fractionCompleted` is still useful for me behind the scenes, despite using an indeterminate indicator.

**Comment by CharlesJS** [comment]
The usual job of `Progress` is to track the _percentage_ of the overall work which is given at any given time, and to send notifications along the way so that you can update a progress indicator. It's a lot of unnecessary overhead if you're just tracking a binary 'done' state.

**Comment by CharlesJS** [comment]
Could you let me know what you're using `fractionCompleted` for behind the scenes?
