### ISSUE TITLE
FractionCompletedNotification should be called if fraction is 1, regardless of granularity

### ISSUE THREAD

**Issue by lmcd** [CharlesJS/CSProgress#5]
Sometimes `FractionCompletedNotification`s are not called if `fractionCompleted` is `1`, but we're below the granularity threshold. This can often mean that the last notification you receive will have a fraction of `0.999...`

**Comment by CharlesJS** [comment]
Do you have a simplified test case that demonstrates this issue, so I can use that to troubleshoot it?

**Comment by CharlesJS** [comment]
Closing this ticket as I have not been able to reproduce it.

**Comment by mickeyl** [comment]
I have just stumbled about the same issue using a progress instance with a parent/child relationship. I didn't create a minimal reproducing example yet, but I'm fairly sure I can produce one. For now the patch

```swift
diff --git a/Sources/CSProgress/CSProgress.swift b/Sources/CSProgress/CSProgress.swift
index deac12f..a891161 100644
--- a/Sources/CSProgress/CSProgress.swift
+++ b/Sources/CSProgress/CSProgress.swift
@@ -600,7 +600,7 @@ public final class CSProgress: CustomDebugStringConvertible {
                     parent.sendFractionCompletedNotifications(fractionCompleted: parent.backing.fractionCompleted, isCompleted: parent.backing.isCompleted, completionHandler: completionHandler)
                 }
             }
-        } else if abs(fractionCompleted - lastNotifiedFractionCompleted) >= self.granularity {
+        } else if isCompleted || abs(fractionCompleted - lastNotifiedFractionCompleted) >= self.granularity {
             let completedUnitCount = self.backing.completedUnitCount
             let totalUnitCount = self.backing.totalUnitCount
```

seems to fix it for my case.

**Comment by CharlesJS** [comment]
Thanks! I committed the change to version 1.1.2. Does this solve the issue for you?

**Comment by mickeyl** [comment]
Yes, it does. Thanks for the prompt action!
